version: '3.8'
services:
  scribe_db:
    image: mariadb:latest
    restart: unless-stopped
    container_name: scribe_db
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - scribe_data:/var/lib/mysql
      - ./CONFIG/scribe_database.sql:/docker-entrypoint-initdb.d/scribe_database.sql
    ports:
      - "96:3306" # Map port 96 on host to 3306 in container (Scribe DB)
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - scribe_int_network
  scribe_app:
    image: mwcurtis20/scribe_app:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scribe_app
    environment:
      - BRUH=${BRUH} # Don't question it
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_SERVER=${SMTP_SERVER}
      - FRONTEND_URL=${FRONTEND_URL}
      - DATABASE_CONNECTOR=${DATABASE_CONNECTOR}
    volumes:
      - scribe_persist_frontend:/app/.nicegui
      - scribe_persist_backend:/app/flask_session
      - scribe_logs:/app/LOGS
    ports:
      - "97:8000" # Map port 97 on host to 8000 in container (FastAPI Backend)
      - "98:8080" # Map port 98 on host to 8080 in container (NiceGUI Frontend)
    links:
      - scribe_db
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:5000/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - scribe_int_network
  phpmyadmin:
    image: phpmyadmin:apache
    restart: unless-stopped
    container_name: scribe_phpmyadmin
    environment:
      - PMA_HOST=scribe_db
      - PMA_PORT=3306
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - UPLOAD_LIMIT=100M
      - APACHE_PORT=99
    ports:
      - "99:99" # Map port 99 on host to 99 in container (Database Management)
    links:
      - scribe_db
    networks:
      - scribe_int_network
  openai-whisper-asr:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: scribe_whisper
    volumes:
      - whisper_persist:/data/whisper
    ports:
      - "95:9000" # Map port 95 on host to 9000 in container (Whisper web service)
    environment:
      ASR_MODEL: base
      ASR_ENGINE: openai_whisper
      ASR_MODEL_PATH: /data/whisper
    restart: unless-stopped
    networks:
      - scribe_int_network
networks:
  scribe_int_network:
    external: false
    name: "scribe_int_network"
volumes:
  scribe_persist_frontend:
    driver: local
  scribe_persist_backend:
    driver: local
  scribe_logs:
    driver: local
  scribe_data:
    driver: local
  whisper_persist:
    driver: local